development:
  adapter: postgresql
  database: h2go_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: h2go_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: h2go_productions
  pool: 5
  timeout: 5000


